---
title: "R for the Student"
author: "JD Long & Dusty Turner"
output: 
  html_document:
    citation_package: biblatex
keep_tex: TRUE
bibliography: bibliography.bib
biblio-style: authoryear
csl: chicago-library-list.csl
link-citations: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## notes to JD

JD - I hacked away and figured out how to do citations inside RMD - an example is below.  You'll have to open up the `bibliography.bib` file to get the full picture.  This is the bibtex element of latex if you are not familiar.

Also, I've had a lot of nights sleep and a lot of beer the night we talked about this.  I like the structure you have below - Is the aim of our article to talk to new users or to talk to people teaching new users.  I tentatively hammered out some stuff on talking to new users - but i feel like its easily transferrable/deletable if I am off track.  

Also, I templated out how to install R/Rstudio -- but then I saw that you had it listed for a different location... and you also mentioned paraphrasing what is in the R Cookbook.  I don't think this is a bad idea.  I paraphrased what we have in our syllabus, ha.  Again, please feel free to hack/delete/move/etc.    

## An example of how to cite in R


With more than 275 practical recipes, this expanded edition [@teetor_long] helps you perform data analysis with R quickly and efficiently. The R language [@R-rmarkdown;@R-knitr] provides everything you need to do statistical work, but its structure can be difficult to master. These task-oriented recipes make you productive with R immediately. Solutions range from basic tasks to input and output, general statistics, graphics, and linear regression.

Each recipe addresses a specific problem and includes a discussion that explains the solution and provides insight into how it works. If you're a beginner, R Cookbook will help get you started. If you're an intermediate user, this book will jog your memory and expand your horizons @grolemund_wickham. You'll get the job done faster and learn more about R in the process.




## Abstract

## Introduction 

## The R Ecosystem

### CRAN 

#### Downloading R

In order to download R follow the following steps:

1) Visit <a href="http://cran.cnr.berkeley.edu" target="_blank">The Comprehensive R Archive Network (CRAN)</a> and click on one of the following:

- `Download R for Windows`
- `Download R for (Mac) OS X`
- `Download R for Linux`

Depending on your operating system, you'll be taken to a different webpage to download a version of `R` that will work on your computer.  

2) If you chose Windows:  

- In the first line at the top of the page, select `install R for the first time`. 
- **RIGHT CLICK** on the top link that should say `Download R 3.6 for Windows` (or something similar depending on the current version of R).  
- Select `Save target as...` and save it to a folder that you can easily find.  
- After the file has downloaded, execute the `.exe` file to install R.  Note: **You may have to right-click and `Run as administrator`.**

2) If you chose MAC:

- Click on the link the link that sayw `R-3.6.0` (or something similar depending on the current version of R).  
<!-- I don't really know what to do from here because the closest thing I have to an apple is an orange in my refrigerator -->

3) If you chose Linux...
<!-- just use an apple or mac... -->


### R Studio

#### Downloading R-Studio

In order to download R-Studio:

1) Visit the <a href="https://www.rstudio.com/products/rstudio/download/" target="_blank">R-Studio Downloads</a> page.  
2) Scroll down the page and **RIGHT CLICK** on the `installer file` for `RStudio 1.2.1335` (or something similar depending on the current version of R Studio) for the operating system you are curently using (Windows, Mac, Linux, etc).
3) Select `Save target as...` and save the file to the same folder that you saved the previous R installation file.  
4) After the file downloads, execute the `.exe` file and install R-Studio.  The first time that you attempt to open R-Studio you may have to search for the program through the search function on your computer.  Once you locate R-Studio, create a shortcut to save it in a location that is easy to find for future use.  

#### R Studio Layout

One of the most common mistakes I run into in class on day one is for beginners to try to run R directly from the console.  They have R Studio downloaded, but do not understand the difference between R and R studio.  R is the program that executes all commands you provide.  It is the engine of the car, if you will.  R Studio is the shell that keeps the user organized.  R Studio is the shell around the car.  To continue, it is the steering wheel, accelerator, brakes, and seatbelts.  

To ensure you have opened R Studio, you screen should be broken into 3 to 4 panels.  

1) Top Right: The Environment
2) Bottom Right: The Files Viewer (what do you call this quadrants?)
3) Bottom Right: The Console
4) Top Left: The Script

Upon first opening R Studio, you may not have panel 4.  In order to open up a script, you will need to select `file` -> `New File` -> `R Script`.

Many new users also make the mistke of not realizing that they have not opened up a script.  They begin executing in the console again and do not take advantage of the ease that scripts provide in writing reproducable code.  

Possibly note on how to execute lines of code.  Both code chuncks and specific lines of code. 

### Tidyverse

## Installation

paraphrase what's in R Cookbook?

### Installing R

### Installing R Studio

### Installing the Tidyverse

## Using R

### Loading Data

### Plotting 

quick intro to ggplot

That graphical tool for ggplot?


### Plotting Multivariate Data

ggpairs?




<!-- When teaching, is the intent to teach coding in R, or is it to use R as an aide to teach statistics?  This will drive what you do and why you do it.   -->

<!-- ### What is the intent of teaching with R? -->

<!-- I have taught advanced introduction to probability and statistics and used R as a tool to teach statistics.  We introduced it by showing how it can be a good calculator -- and along the way taught some of the R Studio functionality (projects/setting working directory, how to execute lines of code, save variables, etc). -->

<!-- I have also taught sabermetrics where we taught coding in R.  So we needed to do data analysis (and we worked under the assumptions that our cadets knew basic statistics) so I taught the coding as a means of data analysis. -->

<!-- ### Do you "give stutents code"? -->

<!-- You have two options:  -->

<!-- 1) Give students code before class.   -->

<!-- The advantage here is that you can talk concepts and the syntax and inevitable mistyping, etc does not inhibit the larger purpose of the instruction.   -->

<!-- The disadvantage is that students don't get intimate with the coding process and learn the necessary skill of trial and error.   -->

<!-- 2) Don't give them code and expect them to keep up.   -->

<!-- The advantage is that cadets are learning the process of coding and "own" the code while they write it.   -->

<!-- The disadvantage is instead of teaching concepts, students are distracted by keeping up with the coding and missing out on the statistics lesson -->

<!-- My recommendation -- you give code if your intent is teaching statistics.  You don't give code if the intent is that cadets learn to code.   -->



# Bibliography

<!-- @grolemund_wickham -->
<!-- @long_teetor -->
<!-- @R-knitr -->
<!-- @R-rmarkdown -->